export var levels={
    1:"Flip krke dikhao tb to manu mai",
    2:"I am hot on one side and cool on the other",
    3:"Kamood ke upar jannat",
    4:"туристические сувениры",
    5:"nosyD[::-1]",
    6:"Potato Eating Inhumane Food",
    7:"My dog runs away sometimes, just saying",
    8:"Always lookup wehn going down",
    9:"I am too poor to afford a car. Need to use a non petrol bases transporation to go to tuition nowadays smh + munirka doesnt have much space for electric powered vehicles anyways. Sad",
    10:"Please use sidewalk for pets",
    11:"L",
    12:"Shortcut to Hell",
    13:"Herbal Garden",
    14:"Peyjal Pump Ghar",
    15:"0-72",
    16:"Bacche ne kiya kand",
    17:"LTZ ko dhundo",
    18:"Let life swing you around",
    19:"Mimic Panel",
    20:"60 degrees on all ends, just sit and relax",
    21:"Trees that breath through air",
    22:"Gate 1 Dora ka map",
    23:"We are here for your security with tons of food",
    24:"P-01 has a cool balcony btw",
    25:"Khelo kudo masti karo",
    26:"Largest Tree",
    27:"Flat benches",
    28:"Catch the person who made LTZ. He is hiding somewhere in the colony."
}