levels=[
    "Flip krke dikhao tb to manu mai",
    "I am hot on one side and cool on the other",
    "Kamood ke upar jannat",
    "туристические сувениры",
    "nosyD[::-1]",
    "Jis cheez se aap maar khate ho (serious wali) + kali",
    "Potato Eating Inhumane Food",
    "My dog runs away sometimes, just saying",
    "Always lookup when going down",
    "I am too poor to afford a car. Need to us a non petrol bases transporation to go to tuition nowadays smh + munirka doesnt have much space for electric powered vehicles anyways. Sad",
    "Please use sidewalk for pets",
    "L",
    "Shortcut to Hell",
    "Herbal Garden",
    "Peyjal Pump Ghar",
    "0-72",
    "Bacche ne kiya kand",
    "LTZ",
    "Let life swing you around",
    "Mimic Panel",
    "60 degrees on all ends, just sit and relax",
    "E - Stick no bills",
    "Trees that breath through air",
    "Gate 1 Dora ka map",
    "We are here for your security with tons of food",
    "P-01 has a cool balcony btw",
    "Khelo kudo masti karo",
    "Largest Tree",
    "Flat benches",
    "Catch the person who made LTZ. He is hiding somewhere in the colony."
]